<?php

namespace AppBundle\Repository;

/**
 * ImportanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImportanceRepository extends \Doctrine\ORM\EntityRepository
{
}
