<?php

namespace AppBundle\Repository;

/**
 * TacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TacheRepository extends \Doctrine\ORM\EntityRepository
{
  public function findallsorted()
  {
      return $this->createQueryBuilder('t')
          ->where('t.effectuee = :effectuee')
          ->setParameter('effectuee', false)
          ->innerJoin('t.importance', 'imp')
          ->addOrderBy('imp.poids', 'ASC')
          ->addOrderBy('t.date', 'ASC')
          ->getQuery()
          ->getResult()
      ;
  }

  public function findallcompleted()
  {
      return $this->createQueryBuilder('t')
          ->where('t.effectuee = :effectuee')
          ->setParameter('effectuee', true)
          ->addOrderBy('t.date', 'ASC')
          ->getQuery()
          ->getResult()
      ;
  }

}
